spring.application.name=userService

server.servlet.context-path=/api/v1/users
server.port=9020

spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=postgres
spring.datasource.password=root1234
spring.jpa.hibernate.ddl-auto=update

jwt.secretKey = akssfjdgtrjgoro7eofpep2epo3wrio3efie9fie0o
